package com.example.myapplication.envs

const val BASE_URL_MANIA = "http://www.maniadb.com/api/search/"
const val TAG = "tst5"
const val YOUTUBE_API_KEY = "AIzaSyDsQ5kAvZdaahvkbFcpIMFvIJSfbmD9d6c"
const val BASE_URL_YOUTUBE = "https://www.googleapis.com/"
const val TAG_D = "DEBUGGING"
const val PLAYLIST_ID_1 = "PLTEt9GGT1Dc0Q0Cw2q-UtAjx0N6Pm1FXZ"
const val PLAYLIST_ID_2 = "PLTEt9GGT1Dc3V4y3J9Ijtw8kW-PTA8UH-"
const val PLAYLIST_ID_3 = "PLTEt9GGT1Dc0XFOBCwccgn62IL3JhQ7cc"
const val PLAYLIST_ID_4 = "PLTEt9GGT1Dc3umrX75GsFTqLDgAuvlC9H"
const val PLAYLIST_ID_5 = "PLTEt9GGT1Dc1FA57_Qt7_MjD8pgt0Yq9m"
const val PLAYLIST_ID_6 = "PLTEt9GGT1Dc2H0Yf3zuXJSMdzYTmdCCvE"
const val PLAYLIST_ID_7 = "PLTEt9GGT1Dc3a5BSvcdY-S6bVnx1HYLqq"
const val PLAYLIST_ID_8 = "PLTEt9GGT1Dc2qpxaK0C6FOKxABIbUn5Fe"
const val PLAYLIST_ID_9 = "PLTEt9GGT1Dc3--Qt4Gc-UZAeFzHnRbyM6"